version: 2
updates:
    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: monthly
          time: '04:00'
          timezone: Europe/Berlin
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
          time: '04:00'
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      versioning-strategy: increase
    - package-ecosystem: npm
      directory: 'packages/iobroker.vis-2'
      schedule:
          interval: monthly
          time: '04:00'
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      versioning-strategy: increase
    - package-ecosystem: npm
      directory: 'packages/iobroker.vis-2/src-vis'
      schedule:
        interval: monthly
        time: '04:00'
        timezone: Europe/Berlin
      open-pull-requests-limit: 5
      versioning-strategy: increase
    - package-ecosystem: npm
      directory: 'packages/types-vis-2'
      schedule:
        interval: monthly
        time: '04:00'
        timezone: Europe/Berlin
      open-pull-requests-limit: 5
      versioning-strategy: increase
